f=open("c:\\users\\Administrator s\\Desktop\\pythonlab\\3.5string convert into list.py","r")
data=f.read()
lw=data.split()
print("Total number of words in a given file is:",len(lw))
print("Available words are:",lw)
